name: fox_tales
description: Easy and secure sharing of images.
publish_to: 'none'
version: 0.0.4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_dotenv: ^5.1.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  path: ^1.8.3
  badges: ^3.1.2
  flutter_windowmanager: ^0.2.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
  fonts:
    - family: Tahu
      fonts:
        - asset: assets/fonts/Tahu.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon_ios.png"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
